image: gcr.io/dynatrace-demoability/productcatalogservice:dd747d8-dirty


replicaCount : 1

service:
  name: grpc
  type: ClusterIP
  port: 3550
  targetport: 3550

container: 
  name: server
  containerport: 3550

  extraEnv:
    - name: PORT
      value: "3550"
  # - name: DISABLE_STATS
  #   value: "1"
  # - name: DISABLE_TRACING
  #   value: "1"
  # - name: DISABLE_PROFILER
  #   value: "1"
  # - name: JAEGER_SERVICE_ADDR
  #   value: "jaeger-collector:14268"
  
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi