container:
  containerport: 3550
  extraEnv:
  - name: PORT
    value: "3550"
  name: server
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
image: gcr.io/dynatrace-demoability/productcatalogservice:dd747d8-dirty
replicaCount: 1
service:
  name: grpc
  port: 3550
  targetport: 3550
  type: ClusterIP
