apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: productcatalog
    service: productcatalogservice
    product: hipster-shop
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
