apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: productcatalogservice
spec:
  host: productcatalogservice.onlineboutique-staging.svc.cluster.local
